config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'
  resources :guides 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guide.rb
class Guide < ActiveRecord::Base
    validates :plantname, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController 
    before_action :set_guide, only: [:edit, :update, :show, :destroy]
    

    def new
        @guide = Guide.new
    end
    def create
        @guide = Guide.new(guide_params)
        if @guide.save
            flash[:notice] = "The guide was suscessfully created"
            redirect_to guide_path(@guide)
        else 
            render "new"
        end
    end

    def show
        
    end

    def edit
        
    end

    def update
        
        if @guide.update(guide_params)
            flash[:notice] = "Guide was Updated"
            redirect_to guide_path(@guide)
        else
            flash[:notice] = "Failed"
            render 'edit'
        end
    end

    def index
        @guides = Guide.all
    end

    def destroy
        
        @guide.destroy
        flash[:notice] = "Guide deleted"
        redirect_to root_path
    end

    private
    def guide_params
        params.require(:guide).permit(:plantname, :description)
    end

    def set_guide
        @guide = Guide.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @guides = Guide.all
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guides/_form.html.erb
<% if @guide.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@guide.errors.count, "error") %>
      Failed:
     </h2>
     <div class="panel-body">
      <ul>
       <% @guide.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>


<div class="row">
    <div class="col-xs-12">
        <%= form_for(@guide, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :plantname %>
            </div>
            <div class="col-sm-6">
                <%= f.text_field :plantname, class: "form-control", placeholder: "Title of guide", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-6">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of guide" %>
            </div>
        </div> 
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-large' %>
            </div>
        </div>
        <% end %>
    </div>
</div>
    
    

app/views/guides/edit.html.erb
<h1>Create a guide</h1>

<%= render 'form' %>


app/views/guides/new.html.erb
<h1>Create a guide</h1>

<%= render 'form' %>


    

app/views/guides/show.html.erb
<h2 align="center">Title: <%= @guide.plantname %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <h4 class="center"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@guide.description) %><br>
 <br>

<%= link_to 'Delete', guide_path(@guide), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "Are you sure?"} %> |
<%= link_to "Edit", edit_guide_path(@guide), class: "btn btn-xs btn-primary" %> |
<%= link_to 'Back', root_path, class: "btn btn-xs btn-success" %>

app/views/layouts/_navigation.html.erb
<div class="Navbar">
   <div class="Navbar__Link Navbar__Link-brand">
      Website title
    </div>
    <div class="Navbar__Link Navbar__Link-toggle">
      <i class="fas fa-bars"></i>
    </div>
  <nav class="Navbar__Items">
    <div class="Navbar__Link">
      Longer Link
    </div>
    <div class="Navbar__Link">
      Longer Link
    </div>
    <div class="Navbar__Link">
      Link
    </div>
  </nav>
  <nav class="Navbar__Items Navbar__Items--right">
    <div class="Navbar__Link">
      Link
    </div>
    <div class="Navbar__Link">
      Link
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <script src="https://kit.fontawesome.com/d088a14a50.js" crossorigin="anonymous"></script>
    <title>PlantApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="assets/javascripts/application.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navigation' %>
    <% flash.each do |name, msg| %>
    <ul>
     <li><%= Guide %></li>
     </ul>
     <% end %>

     <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Blog</h1>
<%= link_to 'About', about_path %>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to The Urban Farmer App</h1>
<%= link_to 'About', about_path %>
<%= link_to 'Home', root_path %>

<h1 align="center">Guides</h1>
<p>
<%= link_to "Create New", new_guide_path %>

<% @guides.each do |guide| %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="guide-plantname">
     <%= link_to guide.plantname, guide_path(guide) %>
    </div>
    <div class="guide-body">
     <%= truncate(guide.description, length: 100) %>
    </div>
    </div>
  </div>
 </div>
<% end %>



   
